483 project update request
AMPnet/project-service pull request #32
Opened 2020-09-29 13:26 UTC by josipkoncurat

2020-09-29 14:41 UTC, githinho requested changes

2020-09-29 14:41 UTC, githinho commented on src/main/kotlin/com/ampnet/projectservice/service/impl/ProjectServiceImpl.kt
> +        serviceRequest.documentSaveRequests?.forEach {
Store documents in parallel.
```suggestion
        serviceRequest.documentSaveRequests?.parallelStream()?.forEach {
```

2020-09-30 08:29 UTC, githinho approved these changes
Waiting for confirmation from frontend team. @mightymatth, please provide info when we can merge this and deploy on staging.

2020-09-30 09:45 UTC, josipkoncurat commented
@mightymatth Do you prefer for the "request" to be nullable in case you are just updating documents or main image. Or we should leave it as non null, which in the above case you would need to pass {} as request body.

2020-10-12 11:27 UTC, merged